on: [push]

jobs:

  test:
    runs-on: ubuntu-latest

    steps:

      # https://www.swi-prolog.org/build/PPA.html
      # https://launchpad.net/~swi-prolog/+archive/ubuntu/devel
      - name: Install SWI-Prolog development version
        run: |
          sudo apt-get install -y software-properties-common
          sudo apt-add-repository ppa:swi-prolog/devel
          sudo apt-get update
          sudo apt-get install -y swi-prolog-nox=8.3.22

      - name: Test coverage
        run: swipl -g "[library(test_cover)]" -t "show_coverage(run_tests)"
