on: [push]

jobs:

  test-cover:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # https://www.swi-prolog.org/build/PPA.html
      # https://launchpad.net/~swi-prolog/+archive/ubuntu/devel
      - name: Install SWI-Prolog development version
        run: |
          sudo apt-get install -y software-properties-common
          sudo apt-add-repository ppa:swi-prolog/devel
          sudo apt-get update
          sudo apt-get install -y swi-prolog=8.3.22-2-gedd88f570-focalppa2

      - name: Check installation
        run: swipl -t check_installation

      - name: Test coverage
        run: |
          :- pwd.
          :- attach_packs(..).
          :- pack_list_installed.
          :- [library(test_cover)].
          :- show_coverage(run_tests).
        shell: swipl -s {0} -t halt
